name:                blockchain-network
version:             0.0.1
synopsis:            Generic blockchain implementation.
description:         Please see README.md
homepage:            https://github.com/TGOlson/blockchain
license:             BSD3
author:              Tyler Olson
maintainer:          tydotg@gmail.com
copyright:           2017 Tyler Olson
category:            Blockchain
extra-source-files:
  - README.md

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DataKinds
  - DefaultSignatures
  - DeriveGeneric
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeOperators

dependencies:
  - aeson
  - async
  - base >= 4.7 && < 5
  - blockchain
  - bytestring
  - either
  - http-client
  - mtl
  - optparse-generic
  - servant
  - servant-client
  - servant-server
  - stm
  - time
  - warp

library:
  source-dirs: lib
  exposed-modules:
    - Network.Blockchain.API
    - Network.Blockchain.Client.Node
    - Network.Blockchain.Client.Wallet
    - Network.Blockchain.Node
