resolver: lts-8.19

packages:
  - .
  - location:
      git: git@github.com:TGOlson/blockchain.git
      commit: master

extra-deps:
  - QuickCheck-2.10.0.1 # current stackage version has bug in "once" function
  - quickcheck-instances-0.3.16

flags: {}
extra-package-dbs: []
